In [2]:
# -*- coding: utf-8 -*-
"""
Created on Thu May 19 19:56:04 2023
@author: AM
"""
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
# ENTRADAS
X = [
[1.,1.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,1.,0.,0.,
0.,0.,1.,0.,0.,0.,
0.,1.,0.,0.,0.,0.,
1.,0.,0.,0.,0.,0.],

[0.,1.,1.,1.,1.,0.,
0.,1.,0.,0.,1.,0.,
0.,1.,1.,1.,1.,0.,
0.,1.,0.,0.,1.,0.,
0.,1.,0.,0.,1.,0.,
0.,1.,1.,1.,1.,0.],

[0.,0.,1.,1.,1.,0.,
0.,0.,1.,0.,1.,0.,
0.,0.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.],

[0.,0.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.],

[0.,1.,1.,1.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,1.,0.,0.,
 0.,0.,1.,0.,0.,0.,
 0.,1.,0.,0.,0.,0.,
 0.,1.,1.,1.,1.,0.],

[0.,1.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,1.,1.,1.,1.,0.],

[0.,0.,1.,0.,1.,0.,
0.,0.,1.,0.,1.,0.,
0.,0.,1.,1.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.,
0.,0.,0.,0.,1.,0.],

[0.,0.,1.,1.,1.,0.,
 0.,0.,1.,0.,0.,0.,
 0.,0.,1.,1.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,1.,1.,1.,0.],

[0.,0.,1.,1.,1.,0.,
 0.,0.,1.,0.,0.,0.,
 0.,0.,1.,1.,1.,0.,
 0.,0.,1.,0.,1.,0.,
 0.,0.,1.,0.,1.,0.,
 0.,0.,1.,1.,1.,0.],

[0.,1.,1.,1.,1.,0.,
 0.,1.,0.,0.,1.,0.,
 0.,1.,0.,0.,1.,0.,
 0.,1.,0.,0.,1.,0.,
 0.,1.,0.,0.,1.,0.,
 0.,1.,1.,1.,1.,0.],
]
# SAÍDAS
y1 = [ ['7'], ['8'], ['9'], ['1'], ['2'],['3'], ['4'], ['5'], ['6'], ['0'],]
clf1 = MLPClassifier(solver='lbfgs',activation='logistic', alpha=1e-5,hidden_layer_sizes=(450,450), random_state=1)
clf1.fit(X, y1)
# SAÍDA NUMÉRICA
y2 = [[1.,0.,0.,0.,0.,0.,0.,0.,0.,0.], [0.,1.,0.,0.,0.,0.,0.,0.,0.,0.],[0.,0.,1.,0.,0.,0.,0.,0.,0.,0.], [0.,0.,0.,1.,0.,0.,0.,0.,0.,0.],[0.,0.,0.,0.,1.,0.,0.,0.,0.,0.],[0.,0.,0.,0.,0.,1.,0.,0.,0.,0.],[0.,0.,0.,0.,0.,0.,1.,0.,0.,0.],[0.,0.,0.,0.,0.,0.,0.,1.,0.,0.],[0.,0.,0.,0.,0.,0.,0.,0.,1.,0.],[0.,0.,0.,0.,0.,0.,0.,0.,0.,1.]]
clf2 = MLPClassifier(solver='lbfgs',activation='logistic', alpha=1e-5,hidden_layer_sizes=(450,450), random_state=1)
clf2.fit(X, y2)
# TESTE
T= [0.,0.,1.,1.,0.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.]

T1= [1.,1.,1.,1.,0.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,1.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,0.,0.,0.,1.,0.,
 0.,1.,1.,1.,1.,0.]

T2= [0.,1.,1.,1.,0.,0.,
 0.,0.,0.,0.,0.,0.,
 0.,0.,1.,1.,1.,0.,
 0.,0.,1.,0.,1.,0.,
 0.,0.,1.,0.,1.,0.,
 0.,0.,1.,1.,1.,0.]

# TESTANDO
print("TESTANDO REDE T: ")
print(clf1.predict([T]))
# TESTANDO
print("TESTANDO REDE T: ")
resultado=clf2.predict([T])
print(resultado)
for i in range(len(resultado[0])):
    print("PADRÃO ",i," - RESULTADO: ",resultado[0][i])
    
    
 # TESTANDO
print("TESTANDO REDE T1: ")
print(clf1.predict([T1]))
# TESTANDO
print("TESTANDO REDE T1: ")
resultado=clf2.predict([T1])
print(resultado)
for i in range(len(resultado[0])):
    print("PADRÃO ",i," - RESULTADO: ",resultado[0][i])
    
    # TESTANDO
print("TESTANDO REDE T2: ")
print(clf1.predict([T2]))
# TESTANDO
print("TESTANDO REDE T2: ")
resultado=clf2.predict([T2])
print(resultado)
for i in range(len(resultado[0])):
    print("PADRÃO ",i," - RESULTADO: ",resultado[0][i])   
    
    # No modelo os números eram 1,3, e 6. Com 450/450 neurônios teve apenas 1 acerto, o código confundiu o 8 com 6 e 1 com 9
    
    # No modelo os números eram 1,3, e 6. Com 250/250 neurônios teve apenas 1 acerto, o código confundiu o 8 com 6 e 1 com 9
    
    # No modelo os números eram 1,3, e 6. Com 100/100 neurônios teve apenas 1 acerto, o código confundiu o 8 com 6 e 1 com 9
     
    # No modelo os números eram 1,3, e 6. Com 50/50 neurônios teve apenas 1 acerto, o código confundiu o 8 com 6 e 1 com 9
          
    # No modelo os números eram 1,3, e 6. Com 10/10 neurônios teve apenas 1 acerto, o código confundiu o 8 com 6 e 1 com 9
    
    # No modelo os números eram 1,3, e 6. Com 1000/1000 neurônios teve apenas 2 acerto, o código confundiu o 8 com 6 
      
    # No modelo os números eram 1,3, e 6. Com 850/850 neurônios teve apenas 2 acerto, o código confundiu o 8 com 6 
    
    # No modelo os números eram 1,3, e 6. Com 1500/1500 neurônios teve 3 acertos
    
     # No modelo os números eram 1,3, e 6. Com 2500/2500 neurônios teve 3 acertos
     
     ###Verificamos que o posicionamento dos números na matriz, influencia a identificação do número e não somente a forma do mesmo 

C:\Users\Octavio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


TESTANDO REDE T: 
['1']
TESTANDO REDE T: 
[[0 0 0 1 0 0 0 0 0 0]]
PADRÃO  0  - RESULTADO:  0
PADRÃO  1  - RESULTADO:  0
PADRÃO  2  - RESULTADO:  0
PADRÃO  3  - RESULTADO:  1
PADRÃO  4  - RESULTADO:  0
PADRÃO  5  - RESULTADO:  0
PADRÃO  6  - RESULTADO:  0
PADRÃO  7  - RESULTADO:  0
PADRÃO  8  - RESULTADO:  0
PADRÃO  9  - RESULTADO:  0
TESTANDO REDE T1: 
['3']
TESTANDO REDE T1: 
[[0 0 0 0 0 1 0 0 0 0]]
PADRÃO  0  - RESULTADO:  0
PADRÃO  1  - RESULTADO:  0
PADRÃO  2  - RESULTADO:  0
PADRÃO  3  - RESULTADO:  0
PADRÃO  4  - RESULTADO:  0
PADRÃO  5  - RESULTADO:  1
PADRÃO  6  - RESULTADO:  0
PADRÃO  7  - RESULTADO:  0
PADRÃO  8  - RESULTADO:  0
PADRÃO  9  - RESULTADO:  0
TESTANDO REDE T2: 
['6']
TESTANDO REDE T2: 
[[0 0 0 0 0 0 0 0 1 0]]
PADRÃO  0  - RESULTADO:  0
PADRÃO  1  - RESULTADO:  0
PADRÃO  2  - RESULTADO:  0
PADRÃO  3  - RESULTADO:  0
PADRÃO  4  - RESULTADO:  0
PADRÃO  5  - RESULTADO:  0
PADRÃO  6  - RESULTADO:  0
PADRÃO  7  - RESULTADO:  0
PADRÃO  8  - RESULTADO:  1
PADRÃO  9  - RE